# Site settings
title: Jonathon Baron
email: jonathon.baron@yale.edu
description: > # this means to ignore newlines until "baseurl:"
  Jonathon Baron, PhD Candidate, Yale University Political Science
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jonathonbaron.github.io" # the base hostname & protocol for your site
permalink: /blog/:year/:month/:day/:title

gems:
  - jekyll-sitemap
  - jekyll-google-tag-manager

google_analytics: UA-133370800-1
google_tag_manager:
  container_id: GTM-WQXLV8R

# Build settings
markdown: kramdown
